In [92]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score


In [65]:
df = pd.read_csv('globalterrorismdb_0718dist.csv', encoding='latin1')
df.head(20)

/var/folders/0l/7p55840534935525wycd_n2m0000gn/T/ipykernel_29978/108301053.py:1: DtypeWarning: Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('globalterrorismdb_0718dist.csv', encoding='latin1')


eventid  iyear  imonth  iday approxdate  extended resolution  \
0   197000000001   1970       7     2        NaN         0        NaN   
1   197000000002   1970       0     0        NaN         0        NaN   
2   197001000001   1970       1     0        NaN         0        NaN   
3   197001000002   1970       1     0        NaN         0        NaN   
4   197001000003   1970       1     0        NaN         0        NaN   
5   197001010002   1970       1     1        NaN         0        NaN   
6   197001020001   1970       1     2        NaN         0        NaN   
7   197001020002   1970       1     2        NaN         0        NaN   
8   197001020003   1970       1     2        NaN         0        NaN   
9   197001030001   1970       1     3        NaN         0        NaN   
10  197001050001   1970       1     1        NaN         0        NaN   
11  197001060001   1970       1     6        NaN         0        NaN   
12  197001080001   1970       1     8        NaN         0        NaN   
13  197001090001   1970       1     9        NaN         0        NaN   
14  197001090002   1970       1     9        NaN         0        NaN   
15  197001100001   1970       1    10        NaN         0        NaN   
16  197001110001   1970       1    11        NaN         0        NaN   
17  197001120001   1970       1    12        NaN         0        NaN   
18  197001120002   1970       1    12        NaN         0        NaN   
19  197001130001   1970       1    13        NaN         0        NaN   

    country         country_txt  region  ...  \
0        58  Dominican Republic       2  ...   
1       130              Mexico       1  ...   
2       160         Philippines       5  ...   
3        78              Greece       8  ...   
4       101               Japan       4  ...   
5       217       United States       1  ...   
6       218             Uruguay       3  ...   
7       217       United States       1  ...   
8       217       United States       1  ...   
9       217       United States       1  ...   
10      217       United States       1  ...   
11      217       United States       1  ...   
12       98               Italy       8  ...   
13      217       United States       1  ...   
14      217       United States       1  ...   
15      499  East Germany (GDR)       9  ...   
16       65            Ethiopia      11  ...   
17      217       United States       1  ...   
18      217       United States       1  ...   
19      217       United States       1  ...   

                                             addnotes  \
0                                                 NaN   
1                                                 NaN   
2                                                 NaN   
3                                                 NaN   
4                                                 NaN   
5   The Cairo Chief of Police, William Petersen, r...   
6                                                 NaN   
7   Damages were estimated to be between $20,000-$...   
8   The New Years Gang issue a communiqué to a loc...   
9   Karl Armstrong's girlfriend, Lynn Schultz, dro...   
10                                                NaN   
11                                                NaN   
12                                                NaN   
13                                                NaN   
14  The fire began at 8:30 PM. The Armed Commandos...   
15                                                NaN   
16                                                NaN   
17  One half hour after the bomb explosion, an ano...   
18                                                NaN   
19  The store was a White owned business operating...   

                                               scite1  \
0                                                 NaN   
1                                                 NaN   
2                                                 NaN   
3                                       

In [66]:
remove_columns = ['approxdate', 'resolution', 'related']

df = df.drop(df.loc[:,remove_columns], axis = 1)
df.head(10)

eventid  iyear  imonth  iday  extended  country         country_txt  \
0  197000000001   1970       7     2         0       58  Dominican Republic   
1  197000000002   1970       0     0         0      130              Mexico   
2  197001000001   1970       1     0         0      160         Philippines   
3  197001000002   1970       1     0         0       78              Greece   
4  197001000003   1970       1     0         0      101               Japan   
5  197001010002   1970       1     1         0      217       United States   
6  197001020001   1970       1     2         0      218             Uruguay   
7  197001020002   1970       1     2         0      217       United States   
8  197001020003   1970       1     2         0      217       United States   
9  197001030001   1970       1     3         0      217       United States   

   region                   region_txt   provstate  ... nreleased  \
0       2  Central America & Caribbean         NaN  ...       NaN   
1       1                North America     Federal  ...       NaN   
2       5               Southeast Asia      Tarlac  ...       NaN   
3       8               Western Europe      Attica  ...       NaN   
4       4                    East Asia     Fukouka  ...       NaN   
5       1                North America    Illinois  ...       NaN   
6       3                South America  Montevideo  ...       NaN   
7       1                North America  California  ...       NaN   
8       1                North America   Wisconsin  ...       NaN   
9       1                North America   Wisconsin  ...       NaN   

                                            addnotes  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4                                                NaN   
5  The Cairo Chief of Police, William Petersen, r...   
6                                                NaN   
7  Damages were estimated to be between $20,000-$...   
8  The New Years Gang issue a communiqué to a loc...   
9  Karl Armstrong's girlfriend, Lynn Schultz, dro...   

                                              scite1  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4                                                NaN   
5  "Police Chief Quits," Washington Post, January...   
6                                                NaN   
7  Committee on Government Operations United Stat...   
8  Tom Bates, "Rads: The 1970 Bombing of the Army...   
9  Committee on Government Operations United Stat...   

                                              scite2  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4                                                NaN   
5  "Cairo Police Chief Quits; Decries Local 'Mili...   
6                                                NaN   
7  Christopher Hewitt, "Political Violence and Te...   
8  David Newman, Sandra Sutherland, and Jon Stewa...   
9  Tom Bates, "Rads: The 1970 Bombing of the Army...   

                                              scite3        dbsource INT_LOG  \
0                                                NaN            PGIS       0   
1                                                NaN            PGIS       0   
2                                                NaN            PGIS      -9   
3                                                NaN            PGIS      -9   
4                                                NaN            PGIS      -9   
5  Christopher Hewitt, "Political Violence and 

In [67]:
df.describe()


eventid          iyear         imonth           iday  \
count  1.816910e+05  181691.000000  181691.000000  181691.000000   
mean   2.002705e+11    2002.638997       6.467277      15.505644   
std    1.325957e+09      13.259430       3.388303       8.814045   
min    1.970000e+11    1970.000000       0.000000       0.000000   
25%    1.991021e+11    1991.000000       4.000000       8.000000   
50%    2.009022e+11    2009.000000       6.000000      15.000000   
75%    2.014081e+11    2014.000000       9.000000      23.000000   
max    2.017123e+11    2017.000000      12.000000      31.000000   

            extended        country         region       latitude  \
count  181691.000000  181691.000000  181691.000000  177135.000000   
mean        0.045346     131.968501       7.160938      23.498343   
std         0.208063     112.414535       2.933408      18.569242   
min         0.000000       4.000000       1.000000     -53.154613   
25%         0.000000      78.000000       5.000000      11.510046   
50%         0.000000      98.000000       6.000000      31.467463   
75%         0.000000     160.000000      10.000000      34.685087   
max         1.000000    1004.000000      12.000000      74.633553   

          longitude    specificity  ...     ransomamt   ransomamtus  \
count  1.771340e+05  181685.000000  ...  1.350000e+03  5.630000e+02   
mean  -4.586957e+02       1.451452  ...  3.172530e+06  5.784865e+05   
std    2.047790e+05       0.995430  ...  3.021157e+07  7.077924e+06   
min   -8.618590e+07       1.000000  ... -9.900000e+01 -9.900000e+01   
25%    4.545640e+00       1.000000  ...  0.000000e+00  0.000000e+00   
50%    4.324651e+01       1.000000  ...  1.500000e+04  0.000000e+00   
75%    6.871033e+01       1.000000  ...  4.000000e+05  0.000000e+00   
max    1.793667e+02       5.000000  ...  1.000000e+09  1.320000e+08   

         ransompaid  ransompaidus  hostkidoutcome     nreleased  \
count  7.740000e+02    552.000000    10991.000000  10400.000000   
mean   7.179437e+05    240.378623        4.629242    -29.018269   
std    1.014392e+07   2940.967293        2.035360     65.720119   
min   -9.900000e+01    -99.000000        1.000000    -99.000000   
25%   -9.900000e+01      0.000000        2.000000    -99.000000   
50%    0.000000e+00      0.000000        4.000000      0.000000   
75%    1.273412e+03      0.000000        7.000000      1.000000   
max    2.750000e+08  48000.000000        7.000000   2769.000000   

             INT_LOG       INT_IDEO       INT_MISC        INT_ANY  
count  181691.000000  181691.000000  181691.000000  181691.000000  
mean       -4.543731      -4.464398       0.090010      -3.945952  
std         4.543547       4.637152       0.568457       4.691325  
min        -9.000000      -9.000000      -9.000000      -9.000000  
25%        -9.000000      -9.000000       0.000000      -9.000000  
50%        -9.000000      -9.000000       0.000000       0.000000  
75%         0.000000       0.000000       0.000000       0.000000  
max         1.000000       1.000000       1.000000       1.000000  

[8 rows x 77 columns]

In [68]:
df.dtypes

eventid      int64
iyear        int64
imonth       int64
iday         int64
extended     int64
             ...  
dbsource    object
INT_LOG      int64
INT_IDEO     int64
INT_MISC     int64
INT_ANY      int64
Length: 132, dtype: object

In [77]:

missing_values = df.isnull().sum()
missing_percentage = (missing_values / len(df)) * 100
print("Missing values in each column:")
print(missing_values)
print("\nPercentage of missing values in each column:")
print(missing_percentage)

# Assess critical columns
interested_columns = ['iyear', 'imonth', 'iday', 'country', 'region', 'extended', 'nreleased', 'INT_IDEO', 'INT_LOG', 'INT_MISC']
missing_values_interested = df[interested_columns].isnull().sum()
print("\nMissing values in interested columns:")
print(missing_values_interested)

# Strategy for handling missing values
initial_count = len(df)

# Option 1: Drop rows with critical missing values
df.dropna(subset=['iyear', 'imonth', 'iday', 'country', 'region'], inplace=True)

# Check rows left
if len(df) < initial_count * 0.85:  # More than 15% dropped
    print("Too many rows removed, consider filling missing values instead.")
else:
    print(f"Dropped rows, current count: {len(df)}")

# Option 2: Fill missing values
df['nreleased'].fillna(df['nreleased'].median(), inplace=True)
df['country'].fillna(df['country'].mode()[0], inplace=True)
df['region'].fillna(df['region'].mode()[0], inplace=True)
df['extended'].fillna(0, inplace=True)  # Assuming 0 for neutral state

# Check the final dataframe
print("\nFinal DataFrame shape:")
print(df.shape)
print("\nMissing values after handling:")
print(df.isnull().sum())


Missing values in each column:
eventid     0
iyear       0
imonth      0
iday        0
extended    0
           ..
dbsource    0
INT_LOG     0
INT_IDEO    0
INT_MISC    0
INT_ANY     0
Length: 132, dtype: int64

Percentage of missing values in each column:
eventid     0.0
iyear       0.0
imonth      0.0
iday        0.0
extended    0.0
           ... 
dbsource    0.0
INT_LOG     0.0
INT_IDEO    0.0
INT_MISC    0.0
INT_ANY     0.0
Length: 132, dtype: float64

Missing values in interested columns:
iyear             0
imonth            0
iday              0
country           0
region            0
extended          0
nreleased    171291
INT_IDEO          0
INT_LOG           0
INT_MISC          0
dtype: int64
Dropped rows, current count: 181691

Final DataFrame shape:
(181691, 132)

Missing values after handling:
eventid     0
iyear       0
imonth      0
iday        0
extended    0
           ..
dbsource    0
INT_LOG     0
INT_IDEO    0
INT_MISC    0
INT_ANY     0
Length: 132, dtype: int64


In [78]:
df['nreleased'].fillna(0, inplace=True)

In [69]:
df[['INT_IDEO', 'INT_LOG', 'INT_MISC']].isnull().sum()


INT_IDEO    0
INT_LOG     0
INT_MISC    0
dtype: int64

In [79]:
X = df[['iyear', 'imonth', 'iday', 'country', 'region', 'extended', 'nreleased', 'INT_LOG', 'INT_MISC']]
y = df['INT_IDEO']


In [80]:

categorical_cols = ['country', 'region']
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_encoded = ohe.fit_transform(X[categorical_cols])
X_encoded_df = pd.DataFrame(X_encoded, columns=ohe.get_feature_names_out(categorical_cols))
X_final = pd.concat([X.drop(columns=categorical_cols).reset_index(drop=True), X_encoded_df], axis=1)
X_final.head(10)

iyear  imonth  iday  extended  nreleased  INT_LOG  INT_MISC  country_5  \
0   1970       7     2         0        0.0        0         0        0.0   
1   1970       0     0         0        0.0        0         1        0.0   
2   1970       1     0         0        0.0       -9         1        0.0   
3   1970       1     0         0        0.0       -9         1        0.0   
4   1970       1     0         0        0.0       -9         1        0.0   
5   1970       1     1         0        0.0       -9         0        0.0   
6   1970       1     2         0        0.0        0         0        0.0   
7   1970       1     2         0        0.0       -9         0        0.0   
8   1970       1     2         0        0.0        0         0        0.0   
9   1970       1     3         0        0.0        0         0        0.0   

   country_6  country_7  ...  region_3  region_4  region_5  region_6  \
0        0.0        0.0  ...       0.0       0.0       0.0       0.0   
1        0.0        0.0  ...       0.0       0.0       0.0       0.0   
2        0.0        0.0  ...       0.0       0.0       1.0       0.0   
3        0.0        0.0  ...       0.0       0.0       0.0       0.0   
4        0.0        0.0  ...       0.0       1.0       0.0       0.0   
5        0.0        0.0  ...       0.0       0.0       0.0       0.0   
6        0.0        0.0  ...       1.0       0.0       0.0       0.0   
7        0.0        0.0  ...       0.0       0.0       0.0       0.0   
8        0.0        0.0  ...       0.0       0.0       0.0       0.0   
9        0.0        0.0  ...       0.0       0.0       0.0       0.0   

   region_7  region_8  region_9  region_10  region_11  region_12  
0       0.0       0.0       0.0        0.0        0.0        0.0  
1       0.0       0.0       0.0        0.0        0.0        0.0  
2       0.0       0.0       0.0        0.0        0.0        0.0  
3       0.0       1.0       0.0        0.0        0.0        0.0  
4       0.0       0.0       0.0        0.0        0.0        0.0  
5       0.0       0.0       0.0        0.0        0.0        0.0  
6       0.0       0.0       0.0        0.0        0.0        0.0  
7       0.0       0.0       0.0        0.0        0.0        0.0  
8       0.0       0.0       0.0        0.0        0.0        0.0  
9       0.0       0.0       0.0        0.0        0.0        0.0  

[10 rows x 222 columns]

In [81]:
features_train, features_test, target_train, target_test = train_test_split(X_final, y, test_size=0.2, random_state=42)

In [83]:
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(features_train, target_train)

/Users/rowanahmed/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [87]:
predicted_lr = lr_model.predict(features_test)

In [86]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(features_train, target_train)

RandomForestClassifier(random_state=42)

In [88]:
predicted_rf = rf_model.predict(features_test)

In [89]:
svc_model = SVC()
svc_model.fit(features_train, target_train)

SVC()

In [90]:
predicted_svc = svc_model.predict(features_test)

In [94]:
recall_lr = recall_score(target_test, predicted_lr, average='weighted')
accuracy_lr = accuracy_score(target_test, predicted_lr)
f1_lr = f1_score(target_test, predicted_lr, average='weighted')
matrix_lr = confusion_matrix(target_test, predicted_lr)
report_lr = classification_report(target_test, predicted_lr)

In [96]:
recall_rf = recall_score(target_test, predicted_rf, average='weighted')
accuracy_rf = accuracy_score(target_test, predicted_rf)
f1_rf = f1_score(target_test, predicted_rf, average='weighted')
matrix_rf = confusion_matrix(target_test, predicted_rf)
report_rf = classification_report(target_test, predicted_rf)

In [98]:
recall_svc = recall_score(target_test, predicted_svc, average='weighted')
accuracy_svc= accuracy_score(target_test, predicted_svc)
f1_svc = f1_score(target_test, predicted_svc, average='weighted')
matrix_svc = confusion_matrix(target_test, predicted_svc)
report_svc = classification_report(target_test, predicted_svc)

/Users/rowanahmed/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/rowanahmed/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/rowanahmed/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [99]:
print('recall_lr', recall_lr)
print('accuracy_lr', accuracy_lr)
print('f1_lr', f1_lr)
print('matrix_lr', matrix_lr)
print('report_lr', report_lr)

recall_lr 0.9535485291284845
accuracy_lr 0.9535485291284845
f1_lr 0.9522836870253869
matrix_lr [[18617     2     0]
 [    0 12721   516]
 [    1  1169  3313]]
report_lr               precision    recall  f1-score   support

          -9       1.00      1.00      1.00     18619
           0       0.92      0.96      0.94     13237
           1       0.87      0.74      0.80      4483

    accuracy                           0.95     36339
   macro avg       0.93      0.90      0.91     36339
weighted avg       0.95      0.95      0.95     36339



In [100]:
print('recall_rf', recall_rf)
print('accuracy_rf', accuracy_rf)
print('f1_rf', f1_rf)
print('matrix_rf', matrix_rf)
print('report_rf', report_rf)

recall_rf 0.9802416136932772
accuracy_rf 0.9802416136932772
f1_rf 0.9801874171183651
matrix_rf [[18616     2     1]
 [    0 12917   320]
 [    2   393  4088]]
report_rf               precision    recall  f1-score   support

          -9       1.00      1.00      1.00     18619
           0       0.97      0.98      0.97     13237
           1       0.93      0.91      0.92      4483

    accuracy                           0.98     36339
   macro avg       0.97      0.96      0.96     36339
weighted avg       0.98      0.98      0.98     36339



In [101]:
print('recall_svc', recall_svc)
print('accuracy_svc', accuracy_svc)
print('f1_svc', f1_svc)
print('matrix_svc', matrix_svc)
print('report_svc', report_svc)

recall_svc 0.8760835466028234
accuracy_svc 0.8760835466028234
f1_svc 0.8234069728828177
matrix_svc [[18599    20     0]
 [    0 13237     0]
 [    0  4483     0]]
report_svc               precision    recall  f1-score   support

          -9       1.00      1.00      1.00     18619
           0       0.75      1.00      0.85     13237
           1       0.00      0.00      0.00      4483

    accuracy                           0.88     36339
   macro avg       0.58      0.67      0.62     36339
weighted avg       0.78      0.88      0.82     36339

